package dev.doraemon.client;

import dev.doraemon.entity.DoraemonEntity;
import net.minecraft.client.model.ModelData;
import net.minecraft.client.model.ModelPart;
import net.minecraft.client.model.ModelPartBuilder;
import net.minecraft.client.model.ModelPartData;
import net.minecraft.client.model.ModelTransform;
import net.minecraft.client.model.TexturedModelData;
import net.minecraft.client.render.entity.model.SinglePartEntityModel;
import net.minecraft.util.math.MathHelper;

/**
 * A hand-built, non-humanoid voxel model. No single cuboid can be truly
 * round, so the head and body are each three stacked, tapered tiers
 * (narrow cap -> wide middle -> narrow cap) to fake a rounder silhouette,
 * and stubby round-ish hands/feet are separate parts rather than texture
 * details. No ears -- canon-accurate, since Doraemon famously lost his.
 *
 * The UV layout below was generated by a small packer script (see
 * scratchpad) that computes standard Minecraft box-UV rectangles for every
 * part and packs them without overlap; the numbers here and the painted
 * texture in textures/entity/doraemon.png are derived from the same source
 * so they're guaranteed to line up.
 */
public class DoraemonEntityModel extends SinglePartEntityModel<DoraemonEntity> {

	private static final int TEXTURE_WIDTH = 128;
	private static final int TEXTURE_HEIGHT = 31;

	private final ModelPart root;
	private final ModelPart head;
	private final ModelPart body;
	private final ModelPart armLeft;
	private final ModelPart armRight;

	public DoraemonEntityModel(ModelPart root) {
		this.root = root;
		this.head = root.getChild("head");
		this.body = root.getChild("body");
		this.armLeft = root.getChild("arm_left");
		this.armRight = root.getChild("arm_right");
	}

	public static TexturedModelData getTexturedModelData() {
		ModelData modelData = new ModelData();
		ModelPartData rootData = modelData.getRoot();

		// Head: an empty pivot group (rotated as a unit for look-at) holding
		// three tapered tiers.
		ModelPartData head = rootData.addChild("head", ModelPartBuilder.create(),
				ModelTransform.pivot(0.0f, 14.0f, 0.0f));
		head.addChild("crown",
				ModelPartBuilder.create().uv(0, 0).cuboid(-3.5f, -10.0f, -3.5f, 7, 1, 7),
				ModelTransform.pivot(0.0f, 0.0f, 0.0f));
		head.addChild("main_head",
				ModelPartBuilder.create().uv(28, 0).cuboid(-5.0f, -9.0f, -5.0f, 10, 8, 10),
				ModelTransform.pivot(0.0f, 0.0f, 0.0f));
		head.addChild("chin",
				ModelPartBuilder.create().uv(68, 0).cuboid(-3.5f, -1.0f, -3.5f, 7, 1, 7),
				ModelTransform.pivot(0.0f, 0.0f, 0.0f));

		// Body: another empty pivot group holding its own tapered tiers plus feet.
		ModelPartData body = rootData.addChild("body", ModelPartBuilder.create(),
				ModelTransform.pivot(0.0f, 14.0f, 0.0f));
		body.addChild("shoulders",
				ModelPartBuilder.create().uv(96, 0).cuboid(-3.5f, 0.0f, -2.5f, 7, 2, 5),
				ModelTransform.pivot(0.0f, 0.0f, 0.0f));
		body.addChild("belly",
				ModelPartBuilder.create().uv(0, 18).cuboid(-4.5f, 2.0f, -3.0f, 9, 7, 6),
				ModelTransform.pivot(0.0f, 0.0f, 0.0f));
		body.addChild("base",
				ModelPartBuilder.create().uv(30, 18).cuboid(-3.5f, 9.0f, -2.5f, 7, 2, 5),
				ModelTransform.pivot(0.0f, 0.0f, 0.0f));
		body.addChild("foot_left",
				ModelPartBuilder.create().uv(82, 18).cuboid(-3.0f, 11.0f, -2.0f, 3, 2, 4),
				ModelTransform.pivot(0.0f, 0.0f, 0.0f));
		body.addChild("foot_right",
				ModelPartBuilder.create().uv(82, 18).mirrored().cuboid(0.0f, 11.0f, -2.0f, 3, 2, 4),
				ModelTransform.pivot(0.0f, 0.0f, 0.0f));

		// Arms, each with a flat round-ish hand nested at the tip so it swings
		// along with the arm automatically.
		ModelPartData armLeft = rootData.addChild("arm_left",
				ModelPartBuilder.create().uv(54, 18).cuboid(-1.5f, -1.0f, -1.5f, 3, 8, 3),
				ModelTransform.pivot(4.5f, 15.0f, 0.0f));
		armLeft.addChild("hand_left",
				ModelPartBuilder.create().uv(66, 18).cuboid(-2.0f, -1.0f, -2.0f, 4, 2, 4),
				ModelTransform.pivot(0.0f, 7.0f, 0.0f));

		ModelPartData armRight = rootData.addChild("arm_right",
				ModelPartBuilder.create().uv(54, 18).mirrored().cuboid(-1.5f, -1.0f, -1.5f, 3, 8, 3),
				ModelTransform.pivot(-4.5f, 15.0f, 0.0f));
		armRight.addChild("hand_right",
				ModelPartBuilder.create().uv(66, 18).mirrored().cuboid(-2.0f, -1.0f, -2.0f, 4, 2, 4),
				ModelTransform.pivot(0.0f, 7.0f, 0.0f));

		// The bell, with a tiny loop on top so it doesn't read as a flat tile.
		ModelPartData bell = rootData.addChild("bell",
				ModelPartBuilder.create().uv(96, 18).cuboid(-1.5f, -1.5f, -3.2f, 3, 3, 1),
				ModelTransform.pivot(0.0f, 17.0f, 0.0f));
		bell.addChild("bell_loop",
				ModelPartBuilder.create().uv(104, 18).cuboid(-0.5f, -1.0f, -0.3f, 1, 1, 1),
				ModelTransform.pivot(0.0f, -1.6f, 0.0f));

		return TexturedModelData.of(modelData, TEXTURE_WIDTH, TEXTURE_HEIGHT);
	}

	@Override
	public ModelPart getPart() {
		return this.root;
	}

	private static final float DEGREES_TO_RADIANS = (float) (Math.PI / 180.0);
	private static final float BASE_HEAD_PIVOT_Y = 14.0f;
	private static final float BASE_BODY_PIVOT_Y = 14.0f;

	@Override
	public void setAngles(DoraemonEntity entity, float limbAngle, float limbDistance, float animationProgress,
			float headYaw, float headPitch) {
		this.head.yaw = headYaw * DEGREES_TO_RADIANS;
		this.head.pitch = headPitch * DEGREES_TO_RADIANS;
		this.armLeft.pitch = MathHelper.cos(limbAngle * 0.6662f) * 0.6f * limbDistance;
		this.armRight.pitch = MathHelper.cos(limbAngle * 0.6662f + (float) Math.PI) * 0.6f * limbDistance;

		// A gentle idle bob (independent of walking) so he reads as alive
		// rather than a static prop even when standing still.
		float bob = MathHelper.sin(animationProgress * 0.06f) * 0.6f;
		this.head.pivotY = BASE_HEAD_PIVOT_Y + bob;
		this.body.pivotY = BASE_BODY_PIVOT_Y + bob * 0.5f;
	}
}
